# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests

name: Node.js CI

on: [pull_request, workflow_dispatch]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.3
      uses: actions/setup-node@v2
      with:
        node-version: 12.16.3
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.3
      uses: actions/setup-node@v2
      with:
        node-version: 12.16.3
        cache: 'npm'
    - run: npm ci
    - run: npm test